/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviebookings;
import java.sql.*;

/**
 *
 * @author dell
 */
public class SeatBooking extends javax.swing.JInternalFrame {

    /**
     * Creates new form SeatBooking
     */
    String movie, date, bookingId, type, seat;
    int slot, screen, status;
    
    
    public SeatBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Seat Booking");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Seat(s) Available");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 4, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel5.setText("MOVIE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 126, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setText("SLOT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 126, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 67, 0, 0);
        getContentPane().add(jTextField2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 67, 0, 0);
        getContentPane().add(jTextField3, gridBagConstraints);

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 84, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 22;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 12, 0, 0);
        getContentPane().add(jButton2, gridBagConstraints);

        jButton3.setText("BOOK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 13, 11, 0);
        getContentPane().add(jButton3, gridBagConstraints);

        jLabel2.setText("SEAT NUMBER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 73;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 24, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = 219;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 20, 0, 0);
        getContentPane().add(jTextField4, gridBagConstraints);

        jLabel3.setText("DATE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 126, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 67, 0, 0);
        getContentPane().add(jTextField5, gridBagConstraints);

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 302;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 13, 0, 23);
        getContentPane().add(jTextField1, gridBagConstraints);

        jLabel4.setText("TYPE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 126, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 67, 0, 0);
        getContentPane().add(jTextField6, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jTextField6.setText(null);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        movie = jTextField2.getText();
        slot = Integer.parseInt(jTextField3.getText());
        date = jTextField5.getText();
        type = jTextField6.getText();
        
        seatBook();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        seat = jTextField4.getText();
        
        stBook();
        
        Billing obj = new Billing();
        
        obj.setSize(400,500);
        
        getParent().add(obj);
        
        obj.show();
        
        setVisible(false);
        
        obj.generateBill();
        obj.display();
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    
    public void seatBook()
    {
        String seatLeft="", mov = null, ro = null;
        int total = 0, sl = 0;
               
        Connection con = null;
        Statement stmt = null;
        Statement stmt2 = null;
	ResultSet rs = null;
        ResultSet rs2 = null;
	PreparedStatement pst = null;	
        
	try
	{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","kalam");
			
            System.out.println("Connected");
			
            stmt = con.createStatement();
            			
            rs = stmt.executeQuery("Select screen,movieName,slot from movie");
            
            while(rs.next() && !((movie.equalsIgnoreCase(mov)) && (slot == sl)))
            {
                screen = rs.getInt(1);
                mov = rs.getString(2);
                sl = rs.getInt(3);
            }
            
            System.out.println("stmt");
            
            stmt2 = con.createStatement();
            rs2 = stmt2.executeQuery("select rowNo,totalSeat from seat where type='"+type+"'");
            
            while(rs2.next())
            {
                ro = rs2.getString(1);
                total = rs2.getInt(2);
                seatLeft = seatLeft + remainingSeat(ro,total);
            }
            System.out.println("stmt2");
            
            jTextField1.setText(seatLeft);
            
        }
                
        catch(ClassNotFoundException ex1)
        {
            System.out.println(ex1);
        }
	catch(SQLException ex2)
	{
            System.out.println(ex2);
	}
    }
    
   
    public String createBookingId(String s)
    {
        String temp = date.substring(0,2)+":"+String.valueOf(screen)+":"+String.valueOf(slot)+":"+s.substring(0,1)+":"+s.substring(1,s.length());
        return temp;
    }
    
    public String remainingSeat(String ro, int total)
    {
        String temp=" ", s = null;
        int se, i = 1;
        
        Connection con = null;
        Statement stmt3 = null;
        ResultSet rs3 = null;
        
        try
	{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","kalam");
			
            System.out.println("Connected");
			
            stmt3 = con.createStatement();
            
            rs3 = stmt3.executeQuery("Select seatNo from booking where bookingDate='"+date+"' AND rowNo='"+ro+"' AND screen="+screen+" AND slot="+slot+" order by seatNo");
            
            while(rs3.next() && i<=total)
            {
                se = rs3.getInt(1);
                
                while(i<se)
                {
                    s = String.valueOf(i);
                    temp = temp + ro + s + ",";
                    i++;
                }
                i++;
            }
            while(i<=total)
            {
                    s = String.valueOf(i);
                    temp = temp + ro + s + ",";
                    i++;
            }
        }
                
        catch(ClassNotFoundException ex1)
        {
            System.out.println(ex1);
        }
	catch(SQLException ex2)
	{
            System.out.println(ex2);
	}
        
        return temp;
    }
        
    
    public void stBook()
    {
        String seats[];
        seats = seat.split(",");
        
        Connection con = null;
	PreparedStatement pst = null;	
        
	try
	{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","kalam");
			
            System.out.println("Connected");
			
            pst = con.prepareStatement("insert into booking values(?,?,?,?,?,?)");
            
            for(String x : seats)
            {
                bookingId = createBookingId(x);
                
                pst.setString(1, date);
                pst.setInt(2, screen);
                pst.setInt(3, slot);
                pst.setString(4, x.substring(0,1));
                pst.setInt(5, Integer.parseInt(x.substring(1,x.length())));
                pst.setString(6, bookingId);

                pst.executeUpdate();
                
                bill();
                
            }
            
            
            System.out.println("data inserted");
            
        }
                
        catch(ClassNotFoundException ex1)
        {
            System.out.println(ex1);
        }
	catch(SQLException ex2)
	{
            System.out.println(ex2);
	}
        
    }
    
    public void bill()
    {
        Connection con = null;
	PreparedStatement pst2 = null;	
        
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","kalam");
			
            System.out.println("Connected");
		
            pst2 = con.prepareStatement("insert into bill values(?,?)");
            
            pst2.setString(1, bookingId);
            pst2.setInt(2, 0);

            pst2.executeUpdate();
            
            System.out.println("data inserted");
            
        }
        catch(ClassNotFoundException ex1)
        {
            System.out.println(ex1);
        }
	catch(SQLException ex2)
	{
            System.out.println(ex2);
	}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
